include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # قوانین توصیه‌شده برای Flutter
    avoid_print: false        # در ir_service.dart برای debug استفاده شده (// ignore comment دارد)
    prefer_const_constructors: true
    prefer_const_declarations: true
    unnecessary_const: true
    use_super_parameters: true
    prefer_single_quotes: true
